export default [
    { sigla: "ec", descricao: "Encoberto com chuvas isoladas", icone: "09d" },
    { sigla: "ci", descricao: "Chuvas isoladas", icone: "09d" },
    { sigla: "c", descricao: "Chuva", icone: "09d" },
    { sigla: "in", descricao: "Instável", icone: "10d" },
    { sigla: "pp", descricao: "Possivel Pancadas de Chuva", icone: "09d" },
    { sigla: "cm", descricao: "Chuva pela Manhã", icone: "09d" },
    { sigla: "cn", descricao: "Chuva a noite", icone: "09d" },
    { sigla: "pt", descricao: "Pancadas de chuva a tarde", icone: "09d" },
    { sigla: "pm", descricao: "Pancadas de Chuva pela Manhã", icone: "09d" },
    { sigla: "np", descricao: "Nublado e Pancadas de Chuva", icone: "09d" },
    { sigla: "pc", descricao: "Pancadas de Chuva", icone: "09d" },
    { sigla: "pn", descricao: "Parcialmente Nublado", icone: "04d" },
    { sigla: "cv", descricao: "Chuvisco", icone: "09d" },
    { sigla: "ch", descricao: "Chuvoso", icone: "09d" },
    { sigla: "t", descricao: "Tempestado", icone: "11d" },
    { sigla: "ps", descricao: "Predominio de Sol", icone: "02d" },
    { sigla: "e", descricao: "Encoberto", icone: "04d" },
    { sigla: "n", descricao: "Nublado", icone: "04d" },
    { sigla: "cl", descricao: "Céu claro", icone: "01d" },
    { sigla: "nv", descricao: "Nevoeiro", icone: "04d" },
    { sigla: "g", descricao: "Geada", icone: "13d" },
    { sigla: "ne", descricao: "Neve", icone: "13d" },
    { sigla: "nd", descricao: "Sol com pancadas de chuva", icone: "10d" },
    { sigla: "pnt", descricao: "Pancadas de chuva a noite", icone: "09d" },
    { sigla: "psc", descricao: "Possibilidade de chuva", icone: "09d" },
    { sigla: "pcm", descricao: "Possibilidade de chuva pela manhã", icone: "09d" },
    { sigla: "pct", descricao: "Possibilidade de chuva a tarde", icone: "09d" },
    { sigla: "pcn", descricao: "Possibilidade de chuva a noite", icone: "09d" },
    { sigla: "npt", descricao: "Nublado com pancadas a tarde", icone: "09d" },
    { sigla: "npn", descricao: "Nublado com pancadas a noite", icone: "Nublado com pancadas a noite" },
    { sigla: "ncn", descricao: "Nublado com possibilidade de chuva a noite", icone: "09d" },
    { sigla: "nct", descricao: "Nublado com possibilidade de chuva a tarde", icone: "09d" },
    { sigla: "ncm", descricao: "Nublado com possibilidade de chuva pela manhã", icone: "09d" },
    { sigla: "npm", descricao: "Nublado com pancadas pela manhã", icone: "09d" },
    { sigla: "npp", descricao: "Nublado com possibilidade de chuva", icone: "09d" },
    { sigla: "vn", descricao: "Variação de nebulosidade", icone: "04d" },
    { sigla: "ct", descricao: "Chuva a tarde", icone: "09d" },
    { sigla: "ppn", descricao: "Possibilidade de pancada de chuva a noite", icone: "09d" },
    { sigla: "ppt", descricao: "Possibilidade de pancada de chuva a tarde", icone: "09d" },
    { sigla: "ppm", descricao: "Possibilidade de pancada de chuva de manhã", icone: "09d" }
]